# Generated by Django 5.0.3 on 2024-04-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default='1', upload_to='about'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='project_count',
            field=models.IntegerField(default=0),
        ),
    ]
